[package]
name = "mem_broker"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
log = "0.4.27"
tokio = { version = "1.44.2", features = ["rt", "sync"] }

[dev-dependencies]
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread", "time"] }
